-- MySQL Script generated by MySQL Workbench
-- Sun Nov 22 07:35:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_web_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_web_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_web_db` DEFAULT CHARACTER SET utf8 ;
USE `my_web_db` ;

-- -----------------------------------------------------
-- Table `my_web_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_web_db`.`users` (
  `user_id` INT NOT NULL,
  `email_address` VARCHAR(100) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_web_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_web_db`.`products` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_web_db`.`downloads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_web_db`.`downloads` (
  `downloads_id` INT NOT NULL,
  `user_id` INT NULL,
  `download_date` DATETIME(1) NULL,
  `filename` VARCHAR(50) NULL,
  `product_id` INT NULL,
  `users_user_id` INT NOT NULL,
  `products_product_id` INT NOT NULL,
  PRIMARY KEY (`downloads_id`),
  INDEX `fk_downloads_users_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_downloads_products1_idx` (`products_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_downloads_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `my_web_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_downloads_products1`
    FOREIGN KEY (`products_product_id`)
    REFERENCES `my_web_db`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
